# Site settings
title: "Adrian J Lopez"
description: "Web Developer"
baseurl: "http://jayzamazing.com"
url: "http://jayzamazing.com"
twitter_username: jayzamazing
github_username: jayzamazing
linkedin_username: adrian-lopez/99/341/688
googleplus_username: 108258618753081021419
# Build settings
markdown: kramdown
permalink: pretty
version: 2.76.0
